// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzuoguoqombuhipyhpel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6dW9ndW9xb21idWhpcHlocGVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Mjc0MTgsImV4cCI6MjA1OTQwMzQxOH0.Ot8Puohp4AVK5-tGq-T1KEcXIX8rncaXd0kLc1Up9vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);